# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Loader Properties
minecraft_version=1.21.8
enabled_platforms=fabric,neoforge
fabric_loader_version=0.17.2
neoforge_version=21.8.32
#yarn_mappings=1.21.1+build.3
# Mod Properties
mod_version=0.7.0-alpha.6
maven_group=com.xtracr.realcamera
archives_base_name=realcamera
# Dependencies
fabric_api_version=0.132.0+1.21.8
cloth_config_version=19.0.147
modmenu_version=15.0.0-beta.3
