# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.configuration-cache=false
## Environment Properties
java_version=25
minecraft_version=26.1-snapshot-2
enabled_platforms=fabric,neoforge
fabric_loader_version=0.18.4
neoforge_version=26.1.0.0-alpha.5+snapshot-2
## Mod Properties
mod_id=realcamera
mod_version=0.7.6-beta
mod_group_id=com.xtracr.realcamera
## Dependencies
fabric_api_version=0.141.1+26.1
cloth_config_version=21.11.153
modmenu_version=18.0.0-alpha.3
