name: Bug Report
description: English template for reporting a bug
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        Make sure you're using the latest version of RealCamera, the bug you're reporting has most likely been fixed in the latest update
        （Check if the suffix matches the latest artifact）
        Before reporting a bug, please search for similar issues first and avoid opening duplicate issues

        For all YSM-related questions, please seek help from others or watch configuration model tutorials first
        instead of asking directly in the issue.

  - type: checkboxes
    id: preliminary
    attributes:
      label: I have confirmed that ...
      options:
        - label: I am using the latest version of RealCamera
          required: true
        - label: Unable to reproduce when main feature is disabled
          required: true

  - type: input
    id: minecraft-version-loader
    attributes:
      label: Minecraft Version and Loader
      description: |
        Please specify the game version and your mod loader.

        You can find them at the corner of main menu or in the log while startup.
    validations:
      required: true

  - type: textarea
    id: incompatible-mods
    attributes:
      label: Incompatible Mods
      description: >-
        The mods related to the bug.
        <br>Try to remove unrelated plugins and mods before reporting
      placeholder: 'Mods list here'
      render: 'raw'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >-
        Please describe the issue you encountered in as much detail as possible.
        <br>Clearer and more detailed descriptions will receive higher processing priority
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. Join the game...

        2. Change some settings...

        3. ...

  - type: textarea
    id: logs
    attributes:
      label: Logs & Crash Reports
      description: >-
        You can find error reports in /logs/latest.log and /crash-reports, or use the launcher's export function
        <br>You can upload logs to sites like https://paste.ubuntu.com/ or https://mclo.gs/ and post the link here
        <br>**DO NOT PASTE LARGE LOGS DIRECTLY HERE!!**
      placeholder: 'Drag log file here or use external link'
