name: Bug Report
description: English template for reporting a bug
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        Make sure you're using the latest version of RealCamera, the bug you're reporting has most likely been fixed in the latest update
        （Check if the suffix matches the latest artifact）
        Before reporting a bug, please search for similar issues first and avoid opening duplicate issues

        For all YSM-related questions, please seek help from others or watch configuration model tutorials first
        instead of asking directly in the issue

  - type: checkboxes
    id: preliminary
    attributes:
      label: I have confirmed that ...
      options:
        - label: I am using the latest version of RealCamera
          required: true
        - label: No related issues found in the issue tracker.
          required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: |
        The Minecraft version you are using.

        You can find them at the corner of main menu or in the log while startup.
    validations:
      required: true

  - type: checkboxes
    id: bug-type
    attributes:
      label: 问题类型
      options:
        - label: Bug occurs when enabling main feature
          required: false
        - label: Incompatibility with other mods
          required: false

  - type: textarea
    id: incompatible-mods
    attributes:
      label: Incompatible Mods
      description: >-
        The mods related to the bug
        <br>Reproduce the bug with unrelated mods removed before reporting
      placeholder: 'Mods list here'
      render: 'raw'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >-
        Please describe the issue you encountered in as much detail as possible. 
        <br>Clearer and more detailed descriptions will receive higher processing priority
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. Join the game...

        2. Change some settings...

        3. ...

  - type: textarea
    id: logs
    attributes:
      label: Logs & Crash Reports
      description: >-
        You can find error reports in /logs/latest.log and /crash-reports, or use the launcher's export function
        <br>You can upload logs to sites like https://paste.ubuntu.com/ or https://mclo.gs/ and post the link here
        <br>**DO NOT PASTE LARGE LOGS DIRECTLY HERE!!**
      placeholder: 'Drag log file here or use external link'