name: New Feature Request
description: Suggest an idea for this project
title: "[new feature]: "
labels: [ "new feature" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Check the latest build to confirm the feature is missing.

  - type: textarea
    id: feature-description
    attributes:
      label: What is this feature about?
      description: A clear and concise description of what the feature is.
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: problem-and-solution
    attributes:
      label: What problem does this feature solve?
      description: Please elaborate on its purpose
      placeholder: This feature helps resolve...
    validations:
      required: true

  - type: textarea
    id: ideal-solution
    attributes:
      label: What does your ideal solution look like?
      description: For example, where new buttons or config options should be placed
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any relevant information or screenshots regarding the feature