architectury {
    common(rootProject.enabled_platforms.split(","))
}

dependencies {
    modCompileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Cloth Config
    modCompileOnly("me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
}
